# Copyright 2026 Tony Aiuto
#
# See LICENSE.txt
"""toolchain to wrap the docker CLI found on the system.

Type: @docker_tools//:docker_toolchain_type

Toolchains:
- @docker_tools//:docker_toolchain: provides the docker binary found on $PATH.
  See configure.bzl%find_docker.
"""

exports_files(["defs.bzl.tpl"])
