# Copyright 2026 Tony Aiuto
#
# See LICENSE.txt
"""Repository rule to autoconfigure a toolchain wrapping the `docker` CLI
found on the exec host's PATH.
"""

_BUILD_TPL = """\
# This content is generated by //toolchains/docker:configure.bzl
load(":defs.bzl", "docker_toolchain")

toolchain_type(
    name = "docker_toolchain_type",
    visibility = ["//visibility:public"],
)

docker_toolchain(
    name = "docker_auto",
    docker_path = "{docker_path}",
)

toolchain(
    name = "docker_toolchain",
    toolchain = ":docker_auto",
    toolchain_type = ":docker_toolchain_type",
    exec_compatible_with = {exec_compatible_with},
)
"""

def _docker_repo_impl(rctx):
    docker_path = rctx.which("docker")

    if rctx.attr.verbose:
        if docker_path:
            print("Found docker at '%s'" % docker_path)  # buildifier: disable=print
        else:
            print("No system docker found.")  # buildifier: disable=print

    rctx.file("BUILD", _BUILD_TPL.format(
        docker_path = str(docker_path) if docker_path else "",
        exec_compatible_with = repr(rctx.attr.exec_compatible_with),
    ))
    rctx.template(
        "defs.bzl",
        Label("//toolchains/docker:defs.bzl.tpl"),
        executable = False,
    )

find_docker = repository_rule(
    implementation = _docker_repo_impl,
    doc = "Create a repository that defines a docker toolchain based on the docker found on the default $PATH.",
    local = True,
    environ = ["PATH"],
    attrs = {
        "exec_compatible_with": attr.string_list(
            doc = "exec_compatible_with list to apply to the created toolchain.",
        ),
        "verbose": attr.bool(
            doc = "If true, print status messages.",
        ),
    },
)
